import Head from 'next/head'
import { ethers } from 'ethers';

export default function Home() {
  const onClick = async () => {
    console.log("click");
    if (!window.ethereum) {
      alert('메타마스크를 까세요')
    } else {
      const ethereum = window.ethereum;
      const provider = new ethers.BrowserProvider(ethereum);
      console.log(provider, "provider");
      const data = await provider.send("eth_requestAccounts", []);
      console.log(data);
    }
  }

  return (
    <>
      <Head>
        <title>royalty_market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button onClick={onClick}>지갑연결</button>
      </div>
    </>
  )
}
